### ISSUE TITLE
AQ - OMI NO2

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#1]
Work with OMI to pull in their NO2 product and process into something that we can use in the dashboard.

**Comment by olafveerman** [comment]
Notes from a conversation with Barry Lefer, program manager of the Tropospheric Composition Program (TCP) at NASA. This group manages the [Ozone Monitoring Instrument (OMI)](https://aura.gsfc.nasa.gov/omi.html) at NASA.

They produce a couple of air quality products:

- NO2 - molecule produced by combustion (oil, coal, gasoline). Short life-time, only sticks around for a couple of hours. Good indicator of economic activity
- SO2 - interesting if we want to look into shippping activity (they see shipping lanes on their product). Also useful for volcanoes, certain industrial smelters, and oil production. 
- Ozone
- Formaldahyde - can be used for economic activity but gives weaker signal and is often detected downwind of source.

For NO2 they procude daily, 15-day rolling average estimates. This is then compared against a 5 year baseline for the same time window.

ESA has a newer Tropomi satellite. Much higher resolution (4x4km), but has only been around for 2 years. Less calibrated, less comparison to baseline.

The instrument doesn't see through clouds + has issues. A couple of years ago a piece of lining came off and is covering part of the sensor. These are some reasons they use a 15-day window and also why they make comparisons to a 5-year baseline. It allows them to fill in data gaps and the cost of detecting fine movements.

Interface ideas discussed with Barry:
* easy comparison to baseline (before / after slider)
* animated timeline of imagery
* graphs to show timeseries estimates per area

GMAO has an NO2 predication model that accounts for atmospheric and weather effects. It hasn't been adapted to account for COVID levels of economic activity. It may be possible to see COVID effect by subtracting actuals out from GMAO model. This will allow you to leverage their built in accounting for non-human effects.  

The TCP Group are funding four research efforts related to COVID research. These may eventually produce datasets that would be useful for the dashboard. Two in particular are:

* Activity at Airports (may be interesting to combine with plane count work) @Geoyi 
* Health effects of air quality

**Comment by olafveerman** [comment]
On Wednesday, I participated in a call with the AQ COVID working group.

Key people:

* Joanna Joiner - leads the OMI group
* Zachary Fasnacht - produces a lot of the current visualizations (static images)
* Lok Lamsal - produces the high-res gridded NO2 data

# Input dataset
Lok Lamsal produces a high-res gridded NO2 .1 * .1 degree. This is a dataset with monthly baselines since 2005.

> If you would like to learn more about the data processing, we have a README file under the “Documentation” tab in this page:
> https://disc.gsfc.nasa.gov/datasets/OMNO2_003/summary
> In this document, you can also find how we create the Level 3 gridded product. 

# Map images
Zach produces map images that get published on the OMI website.

> the maps I showed today are based on 0.1x0.1 degree monthly NO2 data made by Lok Lamsal. They are screened for cloud fraction < 30% and VCD Quality Flag = 0. I believe Lok also removes Row 46 due to possible row anomaly contamination.
> once I grab the data, I am applying a simple Gaussian filter with Scipy in python to  smooth the data a bit. After that, I am just plotting it up.

# Notes on visualizations
The group produces different maps. They found that maps showing % difference are hard to understand by the general public.

**Comment by abarciauskas-bgse** [comment]
I'm working on generating COG's from the https://disc.gsfc.nasa.gov/datasets/OMNO2_003/ product. 

It would be helpful to know:
* If there are specific subdatasets we should be including in the final GeoTiffs
* What is the coordinate reference system or if there is any existing code for georeferencing / projecting the data

Just noting that @drewbo and I are thinking about the architecture for this as well - how to handle both backward and forward processing

@olafveerman @drewbo I could create seperate tickets for each of
1. Creating COGs from source files
2. Backward processing of 2019 to present
3. Forward processing

**Comment by olafveerman** [comment]
Closing this issue. OMI No2 is included in the dashboard. We can open more targeted tickets if we receive feedback.
