### ISSUE TITLE
Monthly timeline

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#116]
Monthly timeline has duplicated labels on the X:

![image](https://user-images.githubusercontent.com/751330/83801694-93403880-a677-11ea-868f-4211419d8357.png)

**Comment by danielfdsilva** [comment]
D3 axis labels are a pain. Basically it tries to create the labels from whatever domain you have, and the available space. You can "suggest" the number of ticks to show, but is really is just a suggestions. And even if you get it right for the current domain, it fails on another.

Given that we also have a popover, I think we should maybe come up with a better system for the domain and apply it throughout all the timelines.
