### ISSUE TITLE
[data, omno2] Process data for dashboard and other requirements (Generate COGs from HDFs/NetCDF)

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/covid-dashboard#12]
### Work so far
Current code which generates a COG (https://gist.github.com/abarciauskas-bgse/1144867ca34f61556d8eb05a507ca01a) is just a straw man. It generates a valid COG but has not been "scientifically validated"

### Information from data set experts

From Zachary Fasnacht:

1. You actually want to use the field /Data_Fields/ColumnAmountNO2TropCloudScreened. This field is the tropospheric NO2 with cloud fraction of greater than 30% screened out (among a few other screens mentioned in the Readme Lok sent along). This is typically what we look at when we are interested in near surface NO2 trends from OMI.
2. The coordinate system for OMI geolocation is WGS84. As far as I am aware, we do not currently have code for converting the data to tif format.

From Lok Lamsal:

We have data in the raster file format at https://avdc.gsfc.nasa.gov/pub/data/satellite/Aura/OMI/V03/L3/OMNO2d_HR/OMNO2d_HRM/. Please take a look at ".dat" files. You might be able to use those data instead.

### Open questions

Are COGs a reasonable representation of this data for what we need to do? Assuming what we need to do is:
1. Visualize the data on a map
2. Generate time series
3. Support ML training

**Comment by rwegener2** [comment]
Closing this issue because the bulk of the data processing is finished we are just tying up some loose ends (addressed in issues #26 and #27)
