### ISSUE TITLE
Special handling for Nightlights VIIRS

### ISSUE THREAD

**Issue by danielfdsilva** [NASA-IMPACT/covid-dashboard#128]
_Flagging as Technical Debt._

The Nightlights VIIRS layer requires a special handling when compared to other layers.
This layer is used in all spotlight areas, however, there are different endpoints for different spotlights.
A property called `{spotlightName}` changes according to the the spotlight being viewed. Different spotlights use the same spotlight name though.
The other difference with this layer is that it has a discrete date domain (all available days are listed instead of a start and end), but the days that are actually available depend on the spotlight being viewed.

Currently the replacement of the `{spotlightName}` and the removal of days from the date domain happens here https://github.com/NASA-IMPACT/covid-dashboard/blob/f9d1bd052b37d08bcc6478b430ced5e344ce85d2/app/assets/scripts/components/spotlight/single/index.js#L263-L288

It may lead to confusion to change layer settings outside the layer file, so it would be good to find a way to handle these exceptions from the layer definition itself. 

Since this may require more changes than what's worth I'd recommend handling this together with the discussion around #89

**Comment by olafveerman** [comment]
@danielfdsilva With the recent changes to how we handle configuration, can you update the status of this issue?

**Comment by danielfdsilva** [comment]
With the implementation of https://github.com/NASA-IMPACT/covid-dashboard/issues/389 and https://github.com/NASA-IMPACT/covid-dashboard/issues/421 in version 1.8.0, this is was addressed.

**Comment by danielfdsilva** [comment]
With the implementation of https://github.com/NASA-IMPACT/covid-dashboard/issues/389 and https://github.com/NASA-IMPACT/covid-dashboard/issues/421 in version 1.8.0, this is was addressed.
