### ISSUE TITLE
[data, omno2] Backward processing to generate COGs from HDFs/NetCDFs from January 2019 to present

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/covid-dashboard#13]
We want to backward process so time series analysis from before COVID period to present is possible.

Right now, I'm thinking we can use AWS batch to parallelize wget of all HDF files, run processing, store the resulting COG on S3.

Note this will not be the only dataset on the platform so to whatever extent we can generalize the pipeline to be configurable, we should do that. We can also consider Cumulus.

**Comment by rwegener2** [comment]
@abarciauskas-bgse Do you think we could close this issue?  As I understand it you have setup terraform to deploy the batch infrastructure and we can use those resources to run batch jobs.  This to me sounds like success for this ticket.

**Comment by abarciauskas-bgse** [comment]
Ok to close!
