### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#130]
Add GA.

[For inspiration.](https://github.com/developmentseed/nasa-apt-frontend/commit/acc1ce4b92eace1074a9d5a2c0e47c4b11aa8d86)

**Comment by jvntf** [comment]
@olafveerman i think this is done already, just need to add the tracking code? see [main.js](https://github.com/NASA-IMPACT/covid-dashboard/blob/ec137bc57f746d0653a92c5b5b1b2cd51fa3b44d/app/assets/scripts/main.js#L43) and [prod config](https://github.com/NASA-IMPACT/covid-dashboard/blob/fd6995458dd54b06ae7051585159a87b6fba4ee6/app/assets/scripts/config/production.js) ?

**Comment by olafveerman** [comment]
Solved here: https://github.com/NASA-IMPACT/covid-dashboard/commit/b343ee7458ca0a3b38cede58b6b1cf6a3c9be06a

**Comment by olafveerman** [comment]
Reopening while we have a final confirmation that this is the right GA to use.

**Comment by olafveerman** [comment]
Did not receive any news that we can't use this GA tracking code. Closing
