### ISSUE TITLE
coastline boundaries missing in UI

### ISSUE THREAD

**Issue by freitagb** [NASA-IMPACT/covid-dashboard#142]
It appears that only country borders are included in the map layer and coastlines are missing. Recommend adding coastlines as another reference layer as is consistently done with most global visualization platforms @olafveerman 
<img width="1136" alt="Screen Shot 2020-06-09 at 3 17 53 PM" src="https://user-images.githubusercontent.com/25142646/84195557-65d30080-aa64-11ea-8964-3e5c4163706a.png">

**Comment by olafveerman** [comment]
Added coastlines from natural earth. They match up fairly well with the country borders.

![image](https://user-images.githubusercontent.com/751330/84443916-92c31700-ac0e-11ea-90e3-39e3cac3523b.png)


It may take a bit for cache to be bust and show up everywhere.
