### ISSUE TITLE
Surface Disturbance Index

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#148]
The Surface Disturbance Index will be provided by JPL/NASA. This is SAR derived and a proxy for human activity. It will be included as an economic indicator in the interface.

Data will be provided later in the month, and include:

* raster data with blue colored pixels indicating a slowdown in human activity. This can be overlaid on the high-res basemap
* indicator data to use as time-series chart (Surface Disturbance Index, 0-1)

## Next step

- science team provides sample data

**Comment by abarciauskas-bgse** [comment]
This dataset as a proxy for human activity sounds very interesting @olafveerman - do we have any more information on this dataset. I'm interested both in the format itself as well as they generate the indication of human activity. I see there's not much in the email thread and not much I can google for.

**Comment by olafveerman** [comment]
> We just uploaded our products (SPM, Slowdown Proxy Map) into S3 bucket.  
> s3://covid-eo-data/slowdown_proxy_map/

@drewbo Did you confirm if these are in the right format?

If so, we can add these to the dashboard.

**Comment by drewbo** [comment]
Confirmed except for nodata values but can be added now while that is addressed

**Comment by olafveerman** [comment]
Next step: figure out how to best visualize SPM in the dashboard.

**Comment by olafveerman** [comment]
Next step:

- [ ] add the data to the dashboard
- [ ] send staging branch to science team
- [ ] send staging branch to EOX

**Comment by olafveerman** [comment]
Sent the staging branch for review. Waiting on feedback about the domain to be able to style correctly.

**Comment by olafveerman** [comment]
This was fixed in [v1.4.1](https://github.com/NASA-IMPACT/covid-dashboard/releases/tag/v1.4.1)
