### ISSUE TITLE
Validate meta tags

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#149]
Replace the placeholder twitter and OG metadata.

Next step: content team to provide tags.

**Comment by olafveerman** [comment]
Title: NASA COVID-19 Dashboard

Descriptor text: Although NASA can't see the novel #coronavirus from space, we can see how our response to it affects the environment. Explore the data using our new experimental dashboard! [link]

**Comment by olafveerman** [comment]
Meta tags added. Keeping this issue open until we've had the chance to validate them on the prod url

**Comment by jvntf** [comment]
outputs from validators

![image](https://user-images.githubusercontent.com/19439427/85429810-43a1ae00-b54d-11ea-9be6-4008b0edb0df.png)
![image](https://user-images.githubusercontent.com/19439427/85429852-50260680-b54d-11ea-94d8-fd76e390d5d7.png)

The tags that the validators claim are missing, are actually present. Is there some redirection issue with the nasa domain?
Not sure how to test / fix this...validator doesn't work with an IP afaik.

cc @danielfdsilva

**Comment by danielfdsilva** [comment]
All fixed.

Twitter:
![image](https://user-images.githubusercontent.com/1090606/85552086-8c736880-b61a-11ea-8719-87adb6c47737.png)

Open Graph
![image](https://user-images.githubusercontent.com/1090606/85552179-a6ad4680-b61a-11ea-9af2-4d67456a6be1.png)

**Comment by danielfdsilva** [comment]
Slack preview (for completeness)
<img width="658" alt="image" src="https://user-images.githubusercontent.com/1090606/85552411-e07e4d00-b61a-11ea-9d5f-c8c94996fa8a.png">
