### ISSUE TITLE
Button to provide feedback

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#153]
Add a button for people to provide feedback, This should probably feed into an existing Earth Data ticketing system.

**Comment by olafveerman** [comment]
Should be integrated with Kayako. Integration docs here: https://fbm.earthdata.nasa.gov/docs/integration

**Comment by olafveerman** [comment]
This is blocked while waiting on the application ID. Sent a reminder this morning.

**Comment by olafveerman** [comment]
App ID: COVID19

**Comment by vgeorge** [comment]
This is how the feedback button looks like:

![feedback](https://user-images.githubusercontent.com/329694/85007217-1e7afd00-b153-11ea-88d4-29ed7b17ab78.gif)

As you can see, the button is a little bit intrusive when displayed over the explore page. There is an option of hidding it and opening manually, so I think we have two ways of implementing this:

1) Use the button provided, displaying only in the about page
2) Create a custom feedback button to open the form. In that case we need to identify where to add it. 

@ricardoduplos @olafveerman what do you think?

**Comment by ricardoduplos** [comment]
The button is indeed intrusive, affecting the overall UX/UI. I suggest to create a custom button as a new menu item.

**Comment by vgeorge** [comment]
Implemented in #192. As the submit function only works from allowed domains, we have to do a final test at the live website to close this.

**Comment by vgeorge** [comment]
Tested from https://earthdata.nasa.gov/covid19, a feedback was sent without errors.
