### ISSUE TITLE
Highlight spotlight areas on map

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#156]
> Need a spotlight marker on map and indication of how many indicators are available at te spotlight.  When clicked should take you to the spotlight location.

@ricardoduplos I believe this may be addressed in the mobile refactor?

**Comment by danielfdsilva** [comment]
Popover structure is ready.
As content it should display the indicators available on each area, but the `/sites` endpoint only returns an array of indicator ids.
```
indicators: ["car-count", "xch4", ...]
```

The human readable labels are also returned by the api, but only when requesting each site individually (e.g. `/sites/be`):
```
"indicators": [
    {
      "id": "car-count",
      "domain": "...",
      "data": "...",
      "notes": null,
      "highlight_bands": null,
      "name": "Car Density Estimate",
      "description": "Car density derived from SAR imagery",
      "attribution": "JAXA, ALOS-2",
      "units": "density per pixel",
      "data-provider": "JAXA",
      "sensor": "ALOS-2/PALSAR-2"
    }
```

We'd also need to have the labels returned in the `/sites` endpoint. Would it be possible to have the same structure but without any data?
@olafveerman @drewbo 

cc @vgeorge

**Comment by danielfdsilva** [comment]
This was implemented
