### ISSUE TITLE
Add footer

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#165]
The site needs a small footer with the NASA responsible. (see https://earthdata.nasa.gov/earth-observation-data/tools for example)

Maybe this is a good spot for the Github link as well? (#163).

This footer doesn't have to exist on the map pages.

cc @ricardoduplos

**Comment by danielfdsilva** [comment]
Fixed with https://github.com/NASA-IMPACT/covid-dashboard/pull/171
