### ISSUE TITLE
Support for indicators without chart

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#167]
Nightlights won't have a chart, but will have a note for some spotlight areas.

**Comment by olafveerman** [comment]
@drewbo Is this something we need to solve on the API side first?

**Comment by drewbo** [comment]
@olafveerman Yeah, right now we won't return the indicator unless there is something at `indicators/[indicator]/[site].csv`. Should it return as long as that _or_ `[site].json` is available?

**Comment by olafveerman** [comment]
Check if it works on the frontend.

**Comment by vgeorge** [comment]
With #293, a indicator without data will not render the chart. It seems this is good to go from implementation side, but @danielfdsilva noticed content issues of [indicators without data in SF](https://8ib71h0627.execute-api.us-east-1.amazonaws.com/v1/sites/sf): 

- Missing `name` property
- Property `notes` is not reflecting the situation on that spot, but a general indicator description

cc @olafveerman

**Comment by olafveerman** [comment]
This is implemented:

![image](https://user-images.githubusercontent.com/751330/85608509-2212f600-b623-11ea-964b-fbcce37236d6.png)
