### ISSUE TITLE
Agriculture product

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#169]
For a second version of the dashboard, we will pull in agricultural products.

**Comment by olafveerman** [comment]
Status update:
@drewbo has been working with Brian Barker to generate the COG. Good progress has been made, there are just some offset issues in the overview files. Once that's resolved, they can be added to the API.

**Comment by drewbo** [comment]
Data is on S3:
- Tile url like https://8ib71h0627.execute-api.us-east-1.amazonaws.com/v1/{z}/{x}/{y}@1x?url=s3%3A%2F%2Fcovid-eo-data%2Fagriculture%2FCropMonitor_{date}.tif&resampling_method=nearest&bidx=1&color_map=custom_cropmonitor
- Dates: ['2020-01-28', '2020-02-28', '2020-03-28', '2020-04-28', '2020-05-28', '2020-06-28']
- custom color map uses [these values](https://github.com/NASA-IMPACT/covid-api/blob/master/covid_api/api/utils.py#L486-L494) for legend
- you can see the whole product at https://8ib71h0627.execute-api.us-east-1.amazonaws.com/simple_viewer.html and insert an s3 link (s3://covid-eo-data/agriculture/CropMonitor_2020_04_28.tif) and use the custom color map which I added to the dropdown (crop monitor)
