### ISSUE TITLE
Nightlights HD for new spotlight areas

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#170]
Data for a couple of new spotlight areas will be provided early next week.

**Comment by olafveerman** [comment]
The HD product for NY was delivered to the S3 bucket.

**Comment by rwegener2** [comment]
New York spotlight area was converted to cog and uploaded to s3.  Filepaths are `s3://covid-eo-data/BMHD_30M_MONTHLY/BMHD_VNP46A2_ny_202004_cog.tif` where that last number is a 4 digit year + a 2 digit month.  There is one file per month from January to June of 2020.

**Comment by olafveerman** [comment]
Great, thanks @rwegener2.

Next step: get this on the dashboard.
