### ISSUE TITLE
CO2

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#172]
Add CO2 to the dashboard.

**Comment by drewbo** [comment]
Data is up at s3://covid-eo-data/xco2/
- NASA provided, global coverage, 0.5x0.625 degree resolution, three products: `mean`, `baseline`, `diff`
- units are % co2 atmospheric concentration, or multiply by 1,000,000 for the more common `ppm`. 
- requests like https://8ib71h0627.execute-api.us-east-1.amazonaws.com/v1/{z}/{y}/{x}@1x?url=s3%3A%2F%2Fcovid-eo-data%2Fxco2%2Fxco2_15day_{product}.{date}.tif&resampling_method=bilinear&bidx=1&rescale=0.0004%2C0.00042
- `baseline` and `mean` should have the same scaling parameters for consistent visualization
- `diff` has units of "difference of...", and we'll need to update the color ramp and scaling factor to `rescale=-0.000001%2C0.000001&color_map=rdbu_r` (although I'd like to confirm this with someone)
-  daily dates from 2020_01_01 to 2020_04_16 (the product is a 15-day rolling average)

cc: @danielfdsilva @olafveerman @rwegener2

**Comment by Schpidi** [comment]
@drewbo thanks, mean and diff work great, but I don't find a valid baseline request

This works: https://8ib71h0627.execute-api.us-east-1.amazonaws.com/v1/0/0/0@1x?url=s3://covid-eo-data/xco2/xco2_15day_mean.2020_04_16.tif&resampling_method=bilinear&bidx=1&rescale=0.0004%2C0.00042

This don't: https://8ib71h0627.execute-api.us-east-1.amazonaws.com/v1/0/0/0@1x?url=s3://covid-eo-data/xco2/xco2_15day_baseline.2020_04_16.tif&resampling_method=bilinear&bidx=1&rescale=0.0004%2C0.00042

Did I misunderstand something?

Also, I had to swap x and y to not end up here:

![Screenshot from 2020-06-17 10-43-10](https://user-images.githubusercontent.com/482265/84878202-cd530680-b089-11ea-820b-11df87971190.png)

![Screenshot from 2020-06-17 10-59-00](https://user-images.githubusercontent.com/482265/84878212-cf1cca00-b089-11ea-9acf-08ae968698e1.png)

**Comment by drewbo** [comment]
@Schpidi my mistake on swapping the x/y, fixed in the url above. Also edited the comment above to fix the other error: that the product is called `base` rather than `baseline`.

**Comment by Schpidi** [comment]
@drewbo awesome, confirmed it works perfectly
