### ISSUE TITLE
URL structure

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#177]
Green light on the proposed URL structure

> * **/explore** - this is the section with the global and spotlight areas. We propose 'explore' because this reflects the interactive nature of the section. Example: /explore/sf
> * **/analysis** - the guided narrative section (to be developed).  Example: /analysis/global-no2-reduction
> * **/indicators** - unchanged, the current indicator pages. Example: /indicators/no2

**Comment by olafveerman** [comment]
No further action here @danielfdsilva ? Can this be closed?

**Comment by danielfdsilva** [comment]
This was implemented
