### ISSUE TITLE
CO2 Gosat

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#183]
Upload CO2 data provided by JAXA to the API.

**Comment by drewbo** [comment]
@olafveerman do you know how this data should appear? Here's what I see when visualizing

<img width="556" alt="Screen Shot 2020-06-16 at 12 55 39 PM" src="https://user-images.githubusercontent.com/7108211/84856777-94894200-b035-11ea-9fac-fe001c5a39d8.png">

**Comment by olafveerman** [comment]
Based on JAXA comment, I believe this is the correct way to display this data.

**Comment by olafveerman** [comment]
@drewbo What's the status of this?

**Comment by drewbo** [comment]
Unmoved from the `covid-eo-jaxa`; I'll rename and swap to the data bucket today

**Comment by drewbo** [comment]
Done; All data uses the form s3://covid-eo-data/xco2/GOSAT_XCO2_{monthly_date}_{site}_BG_circle_cog.tif with some new site names (`dh` for Dhaka, `mb` for Mumbai, `sh` for Shanghai, and `dl` for Delhi). Monthly dates are in the form YYYYMM,  to keep it consistent, data which is 2016-2019 is named 2019

**Comment by Schpidi** [comment]
@drewbo @olafveerman great, confirmed to work as expected. where would I get the polygons for the new sites from? https://8ib71h0627.execute-api.us-east-1.amazonaws.com/v1/sites doesn't seem to have them. thanks

**Comment by olafveerman** [comment]
@Schpidi We don't have those polygons in our API because they were not part of the official spotlight areas.
From your side, is this a nice-to-have or is it breaking something?

**Comment by Schpidi** [comment]
@olafveerman ok, understood. I'll use some manually added polygons than or would you have the bounds of the GeoTIFFs?
