### ISSUE TITLE
Ingest airport / industry JAXA data

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#204]
Provided in COG for Tokyo and Singapore.

> I uploaded 2 COGs to NASA's s3 bucket.
>
> First, I uploaded Tokyo airport monitoring image as economic indicator to [...]/airport/Tokyo/cog/xxxxx_cog.tif
Another, I uploaded Singapore image as industry indicator to [...]/industry/Singapore/cog/xxxx_cog.tif

Once done, provide EOX with details.

**Comment by drewbo** [comment]
Tokyo airport:

tiles like: https://8ib71h0627.execute-api.us-east-1.amazonaws.com/v1/{z}/{x}/{y}@1x?url=s3%3A%2F%2Fcovid-eo-data%2Fairport%2Ftk_20200203.tif&resampling_method=bilinear&bidx=1

(both ALOS and S1A data here)

```
s3://covid-eo-data/airport/tk_2020_01_10.tif
s3://covid-eo-data/airport/tk_2020_02_03.tif
s3://covid-eo-data/airport/tk_2020_03_10.tif
s3://covid-eo-data/airport/tk_2020_03_19.tif
s3://covid-eo-data/airport/tk_2020_04_03.tif
s3://covid-eo-data/airport/tk_2020_05_09.tif
s3://covid-eo-data/airport/tk_2020_05_14.tif
s3://covid-eo-data/airport/tk_2020_06_02.tif
```

Singapore industry:

tiles like: https://8ib71h0627.execute-api.us-east-1.amazonaws.com/v1/{z}/[x}/{y}@1x?url=s3%3A%2F%2Fcovid-eo-data%2Findustry%2Fsg_2020_05_06.tif&resampling_method=bilinear&bidx=1%2C2%2C3

```
s3://covid-eo-data/industry/sg_2020_05_30.tif
s3://covid-eo-data/industry/sg_2020_05_25.tif
s3://covid-eo-data/industry/sg_2020_05_18.tif
s3://covid-eo-data/industry/sg_2020_05_06.tif
s3://covid-eo-data/industry/sg_2020_04_24.tif
s3://covid-eo-data/industry/sg_2020_04_12.tif
s3://covid-eo-data/industry/sg_2020_03_31.tif
s3://covid-eo-data/industry/sg_2020_03_30.tif
s3://covid-eo-data/industry/sg_2020_03_19.tif
s3://covid-eo-data/industry/sg_2020_02_12.tif
s3://covid-eo-data/industry/sg_2020_01_07.tif
```

**Comment by Schpidi** [comment]
@drewbo @olafveerman thanks also for this. I've successfully integrated the Singapore data. It seems transparency is missing:
![Screenshot from 2020-06-20 23-42-58](https://user-images.githubusercontent.com/482265/85212144-0b814c00-b350-11ea-9b5c-0fce7baa831f.png)

**Comment by ikepom** [comment]
Thank you for ingest Singapore image to eodash.
I'll fix them(transparency).

**Comment by ikepom** [comment]
I replace Singapore COGs and I fixed their transparency correctly.
Please check them again.

**Comment by drewbo** [comment]
Reingested, will reset cache now

**Comment by Schpidi** [comment]
thanks! when should we see the change, i.e., when is the cache invalidated? right now I don't see any change.

**Comment by drewbo** [comment]
@Schpidi manually invalidated now, let me know if you see the change

**Comment by Schpidi** [comment]
@drewbo thanks, works now. note, I had to adjust the URL and remove the "%2C2%2C3" in the end.

**Comment by olafveerman** [comment]
Report by @Schpidi in call: Singapore industry data works well. Tokyo airport returns 500's.

**Comment by drewbo** [comment]
@Schpidi can you send me an example error for Tokyo airport?

**Comment by Schpidi** [comment]
I tried various variants (20200514 vs. 2020_05_14, bidx=1 vs. bidx=1%2C2%2C3), this is my current try:

https://8ib71h0627.execute-api.us-east-1.amazonaws.com/v1/15/29117/12900@1x?url=s3%3A%2F%2Fcovid-eo-data%2Fairport%2Ftk_2020_05_14.tif&resampling_method=bilinear&bidx=1

**Comment by drewbo** [comment]
@Schpidi I think your URL is correct, just not over the airport (this is showing Haneda airport, not Narita)

**Comment by Schpidi** [comment]
thanks, good catch. using the right location it magically works, sorry.
