### ISSUE TITLE
Chart ship detection

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#241]
Add a chart with counts to the ship detection layers in SF, NY and LA.

**Comment by drewbo** [comment]
Feature counts per file

```
detections/la/2020_01_22.geojson
41
detections/la/2020_03_15.geojson
12
detections/la/2020_03_21.geojson
20
detections/la/2020_03_22.geojson
86
detections/la/2020_04_23.geojson
20
detections/la/2020_04_24.geojson
28
detections/ny/2020_01_20.geojson
52
detections/ny/2020_01_21.geojson
69
detections/ny/2020_03_18.geojson
44
detections/ny/2020_03_22.geojson
6
detections/sf/2020_03_10.geojson
23
detections/sf/2020_03_11.geojson
23
detections/sf/2020_04_21.geojson
33
```

**Comment by drewbo** [comment]
Added to the API, example at https://8ib71h0627.execute-api.us-east-1.amazonaws.com/v1/sites/la

**Comment by olafveerman** [comment]
Thanks @drewbo 

Next, make sure this shows up in a good chart in LA, NY & SF.

**Comment by danielfdsilva** [comment]
The frontend is ready to show the chart, but there are still some changes needed in the api:

- [ ] Add the `ship-detections` indicator to an indicator group. (currently only no2 is there - #280)
- [ ] Add display data to the api (name, description, attribution, etc)
- [ ] Ensure that the `ship-detections` data is correctly ordered. Value for January coming after April

![image](https://user-images.githubusercontent.com/1090606/85389931-0387fe80-b540-11ea-8b65-1e67fec4e49e.png)

cc @olafveerman @drewbo

**Comment by drewbo** [comment]
@danielfdsilva can you check the order again? I'll work on the other two bullets now

**Comment by drewbo** [comment]
Metadata updated

**Comment by olafveerman** [comment]
Chart is included :boom: .

Closing this issue.
