### ISSUE TITLE
Update and add indicator pages

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#246]
* [x] update NO2
* [x] update nightlights
* [x] add CO2
* [x] add shipping
* [x] add water quality

**Comment by vgeorge** [comment]
The request to add a video to the water quality indicator page was ticketed separately at https://github.com/NASA-IMPACT/covid-dashboard/issues/268.

**Comment by olafveerman** [comment]
All content added. Closing this issue.
