### ISSUE TITLE
Document styling options COG

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#250]
Add information on styling of map layers [to the guidelines.](https://github.com/NASA-IMPACT/covid-api/blob/master/guidelines/raster.md)

* rescaling
* color palettes
* ?

**Comment by drewbo** [comment]
Linked here https://github.com/NASA-IMPACT/covid-api/blob/master/guidelines/raster.md#visualization, let me know if it should be expanded
