### ISSUE TITLE
Add CO2 timeseries

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#251]
Data provided by JAXA to EOX.

**Comment by olafveerman** [comment]
Requested file. Blocked until provided

**Comment by olafveerman** [comment]
Data for Tokyo and Beijing: https://github.com/eurodatacube/eodash/blob/staging/app/public/data/trilateral/N2.csv

**Comment by olafveerman** [comment]
Updated data for Beijing:  [N2_JAXA_Beijing_20200616.zip](https://github.com/NASA-IMPACT/covid-dashboard/files/4819841/N2_JAXA_Beijing_20200616.zip)

**Comment by drewbo** [comment]
Separated into site specific files and uploaded (along with the necessary metadata)

```
upload: co2/ny.csv to s3://covid-eo-data/indicators/xco2/ny.csv
upload: co2/mb.csv to s3://covid-eo-data/indicators/xco2/mb.csv
upload: co2/be.csv to s3://covid-eo-data/indicators/xco2/be.csv
upload: co2/tk.csv to s3://covid-eo-data/indicators/xco2/tk.csv
upload: co2/dl.csv to s3://covid-eo-data/indicators/xco2/dl.csv
upload: co2/dh.csv to s3://covid-eo-data/indicators/xco2/dh.csv
upload: co2/sh.csv to s3://covid-eo-data/indicators/xco2/sh.csv
```
