### ISSUE TITLE
Missing scene Water Quality Tokyo

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#255]
> About map image for water quality, I can see correctly about Tokyo bay. Please see attached Screenshot(png). But I have other problem about Tokyo  bay.
> I can see image in 2020/06/10 by Geotiff but I cannot see anything in eodashboard.org. Please see attached Geotiff.

@drewbo Can you check what is happening with the 2020/06/10 image for Tokyo Bay?

We should get back to Anca about this.

**Comment by drewbo** [comment]
@olafveerman The latest image I see in `s3://covid-eo-jaxa/water_quality/Tokyo/cog/` is for 2020/06/03

**Comment by drewbo** [comment]
Received via email, uploaded to s3://covid-eo-data/oc3_chla_anomaly/anomaly-chl-tk-2020_06_10.tif
