### ISSUE TITLE
Nightlights HD revised

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#258]
Today COB we can expect updated Nightlights HD products for the original spotlight areas.

**Comment by olafveerman** [comment]
On the bucket: 
` s3://covid-eo-blackmarble/COVID_Dashboard_BMHD_Remaining.tar.gz`

**Comment by rwegener2** [comment]
Updated data has been uploaded to s3.  Same filename as before - `BMHD_VNP46A2_be_202001_cog.tif`

**Comment by olafveerman** [comment]
> The latest Black Marble product updates for June are now uploaded on the s3://covid-eo-blackmarble/ repository. As with previous versions, we ask that you update the *entire* time series archive (not just add June-2020)

> Note there has been a slight change in the file format -- i.e., the individual VNP46A2 daily files are now individually compressed as .tar.gz. [...] the files themselves continue to follow the same data structure as previous versions.

**Comment by leothomas** [comment]
- [x] `500M Daily` tiles for LA, NY, SF and EUPorts are now available at `s3://covid-eo-data/BM_500M_DAILY_REDELIVERY`. 

Next steps: 
- [ ] Implement "mosaic-ing" tiles together for Beijing and Tokyo
- [ ] Process `30M Monthly`
- [ ] Overwrite data in `s3://covid-eo-data/BM_500M_DAILY` with new re-delivery (`s3://covid-eo-data/BM_500M_DAILY_REDELIVERY`), once re-delivery data is verified

**Comment by leothomas** [comment]
Update: 
- [x] `500M Daily` tiles for LA, NY, SF and EUPorts are now available at `s3://covid-eo-data/BM_500M_DAILY_REDELIVERY`
- [x] `500M Daily` tiles for Beijing and Tokyo are now available at `s3://covid-eo-data/BM_500M_DAILY_REDELIVERY`

Next Steps: 
- [ ] Process 30M Monthly Tiles
- [ ] Overwrite data in `s3://covid-eo-data/BM_500M_DAILY` the re-delivery 

To Test: 
Run `covid-dashboard` locally and change `BM_500M_DAILY` to `BM_500M_DAILY_REDELIVERY` [here](      `${config.api}/{z}/{x}/{y}@1x?url=s3://covid-eo-data/BM_500M_DAILY/VNP46A2_V011_{spotlightName}_{date}_cog.tif&resampling_method=nearest&bidx=1&rescale=0%2C100&color_map=viridis`)

**Comment by leothomas** [comment]
**Update:**
- [x] 500M Daily tiles for LA, NY, SF and EUPorts are now available at `s3://covid-eo-data/BM_500M_DAILY_REDELIVERY`
- [x] 500M Daily tiles for Beijing and Tokyo are now available at `s3://covid-eo-data/BM_500M_DAILY_REDELIVERY`
- [x] 30M Monthly tiles for all spotlights now available at `s3://covid-eo-data/BMHM_30M_MONTHLY_REDELIVERY`

*Next Steps:*
- [ ] Validate that data is "correct" and overwrite current production data

*Testing* 
Run `covid-dashboard` locally and change `BM_500M_DAILY` to `BM_500M_DAILY_REDELIVERY` [here](https://github.com/NASA-IMPACT/covid-dashboard/issues/%60$%7Bconfig.api%7D/%7Bz%7D/%7Bx%7D/%7By%7D@1x?url=s3://covid-eo-data/BM_500M_DAILY/VNP46A2_V011_%7BspotlightName%7D_%7Bdate%7D_cog.tif&resampling_method=nearest&bidx=1&rescale=0%2C100&color_map=viridis%60)

**Comment by olafveerman** [comment]
Thanks @leothomas . Closing this issue.
