### ISSUE TITLE
Copy Structure of stories

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#261]
Content team would like to remove the title from the homepage stories, and just keep a single sentence.

* Air pollution levels in New York City dropped by as much as 30% during COVID-19 lockdowns.
* While the shelter-in-place mandate was in effect, non-essential businesses were closed, and approximately 6.7 million residents in the San Francisco Bay Area were asked to stay home.
* Los Angeles has the busiest port in the United States, which this year saw a 19% reduction in shipping cargo volumes compared to 2019, according to the Port of Los Angeles.
* Global CO2 concentrations are so large that it is difficult to detect temporary COVID-19-related changes.
* Coronavirus-related shutdowns may affect the amount of algae and sediment in    water bodies. 

@ricardoduplos Should this be styled as the current title or as the body?

**Comment by ricardoduplos** [comment]
Let's use the body.
