### ISSUE TITLE
Add image to CO2 indicator page

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#274]
Add visually compelling image of CO2 to the indicator page.
Maybe from the CO2 diff product

**Comment by jvntf** [comment]
@olafveerman who should be choosing the content of this image?

**Comment by olafveerman** [comment]
@jvntf Please go to the global page, enable the CO2 diff and browse to a timestep that looks interesting to you. Take a screenshot and record the timestep so we add it to the caption.
