### ISSUE TITLE
Add GH resources to /development

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#300]
* release notes
* known issues

**Comment by UAH-DSIG** [comment]
Can we also add links to data submission guidelines? and maybe contribution guidelines? 

And how about adding following paragraph:
This dashboard is built by the NASA Earth Science Data Systems program (link to earthdata.nasa.gov) with help from various science teams and data providers. We are grateful for the many third-party open source projects that we have used.
