### ISSUE TITLE
Content fixes

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#319]
Small text changes highlighted and commented on in these google docs:

* [x] Nightlights https://docs.google.com/document/d/1TQUzayG07kLy0vA8NfLP6Y4gfcHYIGbzN5_H9erriG8/edit
* [x] CO2 https://docs.google.com/document/d/12cG51qkS8fsqCdjQxIJGVVhJvy99nObbwFkd6rJfZnQ/edit
* [x] Water Quality: https://docs.google.com/document/d/1pFzNFFJoOG0PKB78_mnLcfAnfFR9pJEYfXFDXsIt51A/edit
* [x] Shipping https://docs.google.com/document/d/17dUGNlu7pbnhvoSgAwzfo1yKeJJdo3tkf7XvZDSFW2E/edit (also we changed the second image. New image in the images google folder)
* [x] About https://docs.google.com/document/d/1tfwT1Hh0JT6YzNotprUVYAIIfMU1uQtyIOcCUok6_bM/edit
 

I also found some changes that still need to be implemented in the global map. I am going to assume that these cannot be done with the code freeze, but I will note them for the second release:

 

On the global map, some small text changes:

* [x] In the right-hand panel, rename “Economic” to “Economy” (this is a new change, not something you missed)
* [x] For NYC and SF spotlight areas under “Economic” need a separate “Shipping” label (there’s currently only one for Nightlights).
* [x] Text for this shipping label: Travel restrictions and lockdown measures have disrupted the shipping industry and the global economy broadly. NASA researchers are using artificial intelligence to track shipping activities across major ports in the U.S.
* [x] NO2 and CO2 still need to be subscripted in the right-hand panel text for the following spotlight area pages:  
  * https://earthdata.nasa.gov/covid19/explore/global
  * https://earthdata.nasa.gov/covid19/explore/be
  * https://earthdata.nasa.gov/covid19/explore/ny
  * https://earthdata.nasa.gov/covid19/explore/tk
 
On the global map, larger changes:

“Greenhouse Gases”
* [x] Unless someone overruled us (which is fine), I thought we decided not to go with “Greenhouse Gases” in the right-hand panel and keep CO2 under “Air Quality”?
* [x] In either case, need to remove this label from Port of Dunkirk and Port of Ghent because there’s no data there
If we’re keeping it, need to add a label: “Carbon dioxide concentration enhancements” (or whatever we’re seeing in the graphs) for these spotlight areas:
  * [x] https://earthdata.nasa.gov/covid19/explore/be
  * [x] https://earthdata.nasa.gov/covid19/explore/ny
  * [x] https://earthdata.nasa.gov/covid19/explore/tk
* [x] The text for “Greenhouse Gases” for Tokyo is actually for Beijing. Please move this text to Beijing.

**Comment by drewbo** [comment]
assigning myself to make remaining changes on the API

**Comment by drewbo** [comment]
Closed the ones I could on the API (via S3 changes + https://github.com/NASA-IMPACT/covid-api/pull/34). Remaining:
- not sure the decision on the CO2 group
- not sure what content to add or remove for the linked pages

**Comment by olafveerman** [comment]
Made the last changes through a PR in this repo, a PR in the API, and changes to the metadata files on S3.

**Comment by olafveerman** [comment]
Remaining issues addressed with latest API release.
