### ISSUE TITLE
Update text on the "ABOUT" page to reflect that with the addition of NYC, we now have 8 "spotlight" areas

### ISSUE THREAD

**Issue by barrylefer** [NASA-IMPACT/covid-dashboard#326]
-On the ABOUT page, need to change the eight “spotlight” areas with the inclusion now of NYC 
The seven spotlight areas were chosen based on their large populations and high level of economic activity, which reveal significant changes in response to coronavirus lockdown measures.

**Comment by ricardoduplos** [comment]
Fixed. Noting that we now have **7** spotlight areas _and_ **global**.
