### ISSUE TITLE
Before and After COIVD 2020 NO2 Maps that use the 2014-2019 as Baseline Map instead of simple 5 years ago

### ISSUE THREAD

**Issue by barrylefer** [NASA-IMPACT/covid-dashboard#332]
This is similar to the Difference Map request. But in this case, have the monthly 2020 map on the right with the Baseline Map being the 5 year average for the same month.

All of these global datasets for NO2 already exist here with built in slider (see all figures in the Right Column):
https://so2.gsfc.nasa.gov/no2/pix/regionals/Global/Global.html

**Comment by drewbo** [comment]
Closed via #351
