### ISSUE TITLE
Consistency between colorbar and data of CO2 data

### ISSUE THREAD

**Issue by drewbo** [NASA-IMPACT/covid-dashboard#335]
<img width="1205" alt="COVID-19_Dashboard" src="https://user-images.githubusercontent.com/7108211/86788919-b5412800-c034-11ea-8597-772aacc15117.png">

**Comment by olafveerman** [comment]
We need to update the color bar on the legend.

Using this color map:

https://matplotlib.org/3.1.1/gallery/color/colormap_reference.html
divering colormap rdylbu

**Comment by drewbo** [comment]
For a specific set of colors to use in the gradient, try these rgba tuples (from slack):
```
[ 49  54 149 255]
[ 88 140 191 255]
[163 210 229 255]
[232 246 232 255]
[254 232 156 255]
[251 165  92 255]
[226  73  50 255]
```

**Comment by olafveerman** [comment]
Translates into:

```
#313695
#588cbf
#a3d2e5
#e8f6e8
#fee89c
#fba55c
#e24932
```
