### ISSUE TITLE
Add ML detections

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#354]
~- [ ] ships~
- [ ] airports

**Comment by olafveerman** [comment]
Status:

* airplane detection for 5 supersites is ready
* the data has a similar structure compared to the ships

Next step:

@leothomas will see if we can use ship ML scripts to populate backend.

**Comment by olafveerman** [comment]
Planes are ready to go live. We should add LA, SF and NY

http://covideo-plane-detect.surge.sh/

**Comment by lillythomas** [comment]
@olafveerman I believe Tokyo was requested as well.
