### ISSUE TITLE
Add August OMI NO2 data to NASA Dashboard

### ISSUE THREAD

**Issue by barrylefer** [NASA-IMPACT/covid-dashboard#373]
Just a reminder that the August OMI NO2 is ready to go up on the NASA Dashboard

On 8/4/20, 12:21 PM, "Zachary Fasnacht" <zachary.fasnacht@ssaihq.com> wrote:

    Olaf, Drew, and Aimee
    
    I dropped updated July 2020 NO2 files to the S3 bucket yesterday but I 
    do not see this data on the website yet. Can you update the website to 
    show the July data when you get a chance?
    
    Thanks
    
    Zach

**Comment by olafveerman** [comment]
This was fixed in [v1.4.2](https://github.com/NASA-IMPACT/covid-dashboard/releases/tag/v1.4.2)
