### ISSUE TITLE
Add Min/Max values to colorbar scale to NO2 difference plot

### ISSUE THREAD

**Issue by barrylefer** [NASA-IMPACT/covid-dashboard#397]
Would be more useful if NO2 colorbar scale had min/max values.  In order for this to make sense, should also remove the "gamma" adjustment or colorbar slider for NO2 difference plot.

**Comment by olafveerman** [comment]
This was fixed in [v1.4.2](https://github.com/NASA-IMPACT/covid-dashboard/releases/tag/v1.4.2)
