### ISSUE TITLE
Nightlights VIIRS

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#4]
It is possible that we will have access to global nightlights data.

**Comment by olafveerman** [comment]
Tracking both products in separate issues. We'll use this ticket for the global 500 meter product.

**Comment by rwegener2** [comment]
I started pulling together the cog process for the 500m files.  We have been referring to this as a global product, but it looks like they have only delivered a few [grid cells](https://www.researchgate.net/profile/Antonio_Esteves/publication/263199282/figure/fig1/AS:296071151538176@1447600271412/MODIS-tiling-scheme.png).  According to [this comment](https://github.com/developmentseed/satellite_ml_covid19/issues/12#issuecomment-634841940) that was to be expected.  It seems like it doesn't make sense to make a global mosaic of only 7 grids, but maybe it makes the data easier to serve?

@drewbo Are you the one to check in on with this?  It makes the most sense not to mosaic the grids together by day but to save them individually, correct?

**Comment by rwegener2** [comment]
Global 500 m product is cog format in [in s3](https://s3.console.aws.amazon.com/s3/buckets/covid-eo-data/BM_500M_DAILY/?region=us-east-1&tab=overview)

**Comment by danielfdsilva** [comment]
The current daily endpoint `https://8ib71h0627.execute-api.us-east-1.amazonaws.com/v1/6/10/25@1x?url=s3%3A%2F%2Fcovid-eo-data%2FBM_500M_DAILY%2FVNP46A2_V011.h05v05.2020_01_04.5000.76.68_44.97_V30_cog.tif&resampling_method=bilinear&bidx=1&rescale=0%2C1&color_map=viridis` only has data for 1 day and over a piece of California. Is this still expected or am I missing something.
cc @olafveerman @drewbo

**Comment by olafveerman** [comment]
Had a look at the bucket, but there is an issue with the naming scheme:

```
2020-06-03 01:15:15     399837 VNP46A2_V011.h05v05.2020_01_01.5000.109.49_24.41_V30_cog.tif
2020-06-03 01:16:50     411950 VNP46A2_V011.h05v05.2020_01_02.5000.98.88_30.95_V30_cog.tif
2020-06-03 01:16:18     394718 VNP46A2_V011.h05v05.2020_01_03.5000.88.23_36.22_V30_cog.tif
2020-06-03 01:15:14     409362 VNP46A2_V011.h05v05.2020_01_04.5000.76.68_44.97_V30_cog.tif
```

cc @drewbo @abarciauskas-bgse @rwegener2

**Comment by drewbo** [comment]
Confirmed from slack convo that new format will drop the numbers from after the date cc: @rwegener2
