### ISSUE TITLE
Update CO2 product

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#411]
CO2 data was updated to a 16-day average (instead of 15-day) to better reflect the OCO-2 orbit.

New filenames are *_16day_* instead of *_15day_*.

## Next steps

- [x] reorganize data so each dataset is in a folder, to meet requirement `Each dataset should have a 1-1 relationship with a folder.`
- [x] once data is clean, give a headsup to EOX so it can be updated in the trilateral as well.
- [x] write data providers about new structure
- [x] update data in the dashboard
- [x] ensure all descriptions mention 16 day averages

Once it's confirmed that the new data works on the NASA + trilateral dashboard:

- [x] clean old data from the S3 paths. Notably: `xco2-diff-old/`, `xco2-mean-old/` & `xco2/`

**Comment by olafveerman** [comment]
## New locations
The new data products can now be found in these separate folders:

* `s3://covid-eo-data/xco2-mean/`
* `s3://covid-eo-data/xco2-diff/`
* `s3://covid-eo-data/xco2-base/`

Eg. `s3://covid-eo-data/xco2-mean/xco2_16day_mean.2020_07_16.tif`

## Date range
The date range for all three products is `2020_01_01` to `2020_07_16`

## Example
Example request: `${config.api}/{z}/{x}/{y}@1x?url=s3://covid-eo-data/xco2-diff/xco2_16day_diff.{date}.tif&resampling_method=bilinear&bidx=1&rescale=-0.000001%2C0.000001&color_map=rdbu_r`

cc @Schpidi

**Comment by Schpidi** [comment]
Thanks @olafveerman we've updated staging of the trilateral version (https://github.com/eurodatacube/eodash/pull/578/commits/12f7cb57c7432e478123f8f215c19646b4168649) which should soon land in production. 

Please note that we're still using data in the `xco2` path for the CO2 timeseries (cf. https://github.com/eurodatacube/eodash/blob/staging/app/src/config/trilateral.js#L343).

**Comment by olafveerman** [comment]
Fantastic and thanks for the headsup. I've left the GOSAT imagery in the bucket.
