### ISSUE TITLE
Area thumbnails missing

### ISSUE THREAD

**Issue by ricardoduplos** [NASA-IMPACT/covid-dashboard#415]
In the list of spotlight areas, Togo and Great Lakes are missing thumbnails:

<img width="1289" alt="Screen Shot 2020-09-22 at 15 34 54" src="https://user-images.githubusercontent.com/1016701/93896853-557c2400-fce9-11ea-81c0-0e69fd04dd82.png">

**Comment by olafveerman** [comment]
Good catch, thanks.

The one for the Great Lakes is waiting around in this PR: https://github.com/NASA-IMPACT/covid-dashboard/pull/403

We still need to find one for Togo. I started looking and couldn't find one that was appropriate & open license.
