### ISSUE TITLE
Recovery Proxy Map

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#416]
The Recovery Proxy Map is a new data product that should be added to the API and the dashboard. This is scheduled to be included in the tri-lateral dashboard by Wednesday Sep 30.

- [x] upload data to S3 bucket
- [x] make sure product works well on API
- [x] notify EOX
- [x] add product to dashboard

**Comment by olafveerman** [comment]
Data is uploaded to: `s3://covid-eo-data/rpm`

@drewbo Can you have a look and see if this makes sense?

**Comment by drewbo** [comment]
Looks like the format itself is fine and shows up in the viewer; don't have enough context around the data and source to say more than that
