### ISSUE TITLE
Dashboard should load datasets via API

### ISSUE THREAD

**Issue by abarciauskas-bgse** [NASA-IMPACT/covid-dashboard#421]
Right now, datasets are defined statically in https://github.com/NASA-IMPACT/covid-dashboard/tree/develop/app/assets/scripts/components/common/layers

In our vision for making the dashboard configurable, these dataset configurations should be loaded from an API.

In prototyping I have done a bit to work on this, and am interested on feedback on the implementation.

In the dashboard:
* Define props.mapLayers as the result of the datasets api result
    * https://github.com/NASA-IMPACT/covid-dashboard/blob/maap-prototype/app/assets/scripts/components/global/index.js#L503-L507
    * https://github.com/NASA-IMPACT/covid-dashboard/blob/maap-prototype/app/assets/scripts/redux/layer-data.js#L16
* What i don't like about ^^ is the part about the default layers, I would actually like the layer loading to by synchronous because the whole dashboard depends on them

In the API, load dataset json files from S3, https://github.com/NASA-IMPACT/covid-api/blob/maap-prototype/covid_api/db/static/datasets/__init__.py#L28-L36

cc @drewbo

**Comment by drewbo** [comment]
Re: https://github.com/NASA-IMPACT/covid-dashboard/issues/389, retagging as frontend

**Comment by danielfdsilva** [comment]
I spent some time looking into getting the layers from the Api and noticed some strange values:

The `nightlights-viirs` tile url has a `{spotlightName}` parameter which we replace with a value according with the spotlight id (https://github.com/NASA-IMPACT/covid-dashboard/blob/aeb3b87905c7609a6d6426c2fbdbefabefef1b4c/app/assets/scripts/components/common/layers/index.js#L201-L029). But the api is retuning the url with `{spotlightId}` parameter (ex: https://8ib71h0627.execute-api.us-east-1.amazonaws.com/v1/datasets/tk)

It would also be good if all the possible url replacements would be done on the api side, to reduce dependency with the client.
- All the `{spotlightId}` parameters should come replaced from the api, when querying for a specific spotlight.
- The `water-chlorophyll` layer of tokyo requires the `&rescale=-100%2C100` portion of the url to be removed.

I think the only things to be left for the client to replace are the dynamic interactive bits, like the `{date}` and `{gamma}`.

As for implementation, I propose a quick approach for now where we load all the datasets when the page loads and then access them in a static manner.
The homepage alone already requires several datasets for the animation, and some parts of the code assume the datasets as static variable. Keeping it this way may be a "good enough" approach for now, considering that we'll be doing significant development in the near future.

**Comment by olafveerman** [comment]
@danielfdsilva anything left to do on this, or is this fully implemented in 1.8.0?

**Comment by danielfdsilva** [comment]
Implemented in 1.8.0 as described in the comment above
