### ISSUE TITLE
Updated Black Marble data

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#425]
> The latest Black Marble dashboard time series results for spotlight regions (c. Sept 30 2020) are now on: s3://covid-eo-blackmarble/

> COVID_Dashboard_BMHD_Jan_Sep_2020.tar.gz [~1GB]
> COVID_Dashboard_VNP46A2_Jan_Sep_2020.tar.gz [~12.4GB]

**Comment by olafveerman** [comment]
Start using the two-letter code for this product.

```
function handleNightlightsViirs (l, spotlightId) {
  const spotlightName = {
    be: 'Beijing',
    gh: 'EUPorts',
    du: 'EUPorts',
    la: 'LosAngeles',
    ny: 'NewYork',
    sf: 'SanFrancisco',
    tk: 'Tokyo'
  }[spotlightId];
```

leo:
> Ok  - is it difficult to remove that handling from the font end? I’ve updated the /datasets api to filter only based on spotlightId (2 letters), instead of either spotlightId or spotlightName , depending on the dataset

**Comment by olafveerman** [comment]
New Nightlights data is available, with some changes to the file paths cc @Schpidi

## 30m monthly
New path: `s3://covid-eo-data/bmhd_30m_monthly/BMHD_VNP46A2_{spotlightId}_{date}_cog.tif`

Available for 2020-01-01 through 2020-09-01.

## 500m daily
New path: `s3://covid-eo-data/bm_500m_daily/VNP46A2_V011_{spotlightId}_{date}_cog.tif`

Spotlight IDs for the 500m product now follow the two-letter convention:

* `be` - Beijing
* `ca` - Caracas (New area, north of Venezuela and part of Puerto Rico/DR)
* `la` - Los Angeles
* `ny` - New York
* `sf` - San Francisco
* `tk` - Tokyo

Available for 2020-01-01 through 2020-10-02.

**Comment by olafveerman** [comment]
@Schpidi Once you confirm that you're pulling in the new data in the trilateral, we'll clean up the old data.

**Comment by Schpidi** [comment]
This is adjusted in staging. I'll let you know once this is deployed to production.

FYI, we only use the 30m monthly data for now.

**Comment by Schpidi** [comment]
This is now deployed to production.
