### ISSUE TITLE
JAXA WQ Data - 500 error

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#431]
When requesting JAXA Water Quality data, the API returns a 500 error.

Request: 
```
https://8ib71h0627.execute-api.us-east-1.amazonaws.com/v1/12/3584/1631@1x?url=s3://covid-eo-jaxa/wq-chla/jx_chla_tif_kob_2020_08_15.tif&resampling_method=bilinear&bidx=1&color_map=rdbu_r
```

API logs:

```
rasterio.errors.RasterioIOError: '/vsis3/covid-eo-jaxa/wq-chla/jx_chla_tif_kob_2020_08_22.tif' not recognized as a supported file format.
```

Running [the validations](https://github.com/NASA-IMPACT/covid-api/blob/master/guidelines/raster.md#data-structure), the GeoTIFF seems to be :ok_hand: :

```
$ rio cogeo validate jx_chla_tif_kob_2020_08_01.tif 
~/jx_chla_tif_kob_2020_08_01.tif is a valid cloud optimized GeoTIFF
```

```
$ rio info jx_chla_tif_kob_2020_08_01.tif --nodata
255.0
```

cc @Schpidi

**Comment by drewbo** [comment]
@olafveerman I don't think the lambda function has access to the `covid-eo-jaxa` bucket directly (it must be transferred to `covid-eo-data`

**Comment by AlessandroScremin** [comment]
Dears @olafveerman @drewbo

I have this error trying to listing the data on this bucket, just a test to check the download....

aws s3 ls s3://covid-eo-jaxa/wq-chla

but I got this error. SO it seems I need some keys to access it. Could you please check?

An error occurred (InvalidAccessKeyId) when calling the ListObjectsV2 operation: The AWS Access Key Id you provided does not exist in our records.

**Comment by olafveerman** [comment]
We transferred the data to the main bucket used by the API to fix the permission issues. None of the filenames changed.

Could you try again using the following paths?

* `s3://covid-eo-data/oc3_chla_anomaly/`
* `s3://covid-eo-data/tsm/`

Eg.
```
https://8ib71h0627.execute-api.us-east-1.amazonaws.com/v1/12/3584/1631@1x?url=s3://covid-eo-data/oc3_chla_anomaly/jx_chla_tif_kob_2020_08_15.tif&resampling_method=bilinear&bidx=1&color_map=rdbu_r
```

cc @AlessandroScremin @Schpidi

**Comment by Schpidi** [comment]
Thanks for the update. I adjusted the configuration in staging (29a3f65), soon to be on production.

Just a general observation, could the blue color over land be removed?

**Comment by Schpidi** [comment]
This is now deployed to production.

**Comment by olafveerman** [comment]
Fantastic, thanks @Schpidi

**Comment by olafveerman** [comment]
Ah, regarding the blue color over land. That's a question for JAXA.
