### ISSUE TITLE
Update Geoglam

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#433]
[Updated_CropMonitor_Data.zip](https://github.com/NASA-IMPACT/covid-dashboard/files/5372467/Updated_CropMonitor_Data.zip)

- [x] add new scene to bucket
- [x] add to frontend

**Comment by olafveerman** [comment]
Running `$ rio cogeo validate CropMonitor_2020_07_28.tif`

```
The following warnings were found:
- The file is greater than 512xH or 512xW, it is recommended to include internal overviews
```

Fixed this by rerunning `rio cogeo create`

**Comment by aapopescu** [comment]
@olafveerman , cc @lubojr 

the layers from 28 July onwards use a dark shade for no-data at higher zoom levels. 

<img width="1582" alt="Screen Shot 2020-10-22 at 09 54 55" src="https://user-images.githubusercontent.com/35488732/96841934-b152dd80-144c-11eb-82e3-ee6e25c58a2b.png">
