### ISSUE TITLE
Ship detections fetch previous day

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#447]
For certain dates, ship detections show no Planet imagery nor detections. This is because a request is made for data of the previous day. If the user wants to visualize data for May 1st, the interface makes a request for April 30th.

Take for example SF, May 1st:

![image](https://user-images.githubusercontent.com/751330/98803426-a4eaf080-240c-11eb-9333-d2bc89258406.png)

Console:

`GET https://8ib71h0627.execute-api.us-east-1.amazonaws.com/v1/detections/ship/sf/2020_04_30.geojson 404`
`GET https://8ib71h0627.execute-api.us-east-1.amazonaws.com/v1/planet/3/1/3?date=2020_04_30&site=sf net::ERR_FAILED`

Note that it tries to fetch data for April 30th, for which there is none.

cc @danielfdsilva @leothomas

**Comment by danielfdsilva** [comment]
The url is also not being respected. Upon page load, the request is made for the last day of the domain, regardless of the date set in the url
