### ISSUE TITLE
Story visuals - Landsat scenes

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#466]
Several stories rely on Landsat imagery. Working assumption is that we'll be showing single scenes only, no mosaics.
If it turns out that some chapters do require mosaics, we should figure out how to support that.

The process:

1. **search** - for each of the visuals, browse remotepixel.ca to find a good scene. Write down the scene ID, date, and link to remotepixel.ca
2. **download & process**
3. **upload to S3** - upload each scene to `s3://covid-eo-data/standalone/[story]`

## Stories

story | chapter | visual
-- | -- | --
Air | 2:  What Makes Air Quality Good or Bad? | Los Angeles, USA, February 2020; Landsat Image
LCLUC | 1: Changing Behavior and Changing Landscapes | Wuhan, China, Landsat Image February 2020
Water Quality | 1: Water Quality during the COVID-19 Pandemic | The Chesapeake Bay, Landsat Image, April 2020
Water Quality | 6: Counting Crops During a Lockdown | Landsat image of corn/soybean fields in Iowa. [...] a Landsat image over Iowa would be great. We have paid special attention to the area around Des Moines lately
Water Quality | 3: Examining the Chesapeake Bay during COVID-19 | Landsat image Chesapeake Bay, April 2020

@yunica Can you help us with the first step? Finding appropriate scene id's?

**Comment by yunica** [comment]
@olafveerman , I have completed the  Landsat images from `remotepixel.ca` search in this [spreadsheet](https://docs.google.com/spreadsheets/d/1xCLosPJCivbrXHMEv6duUB-pAD4LF6KVj5BJE_LxLco/edit?usp=sharing).

**Comment by olafveerman** [comment]
Fantastic, thanks @yunica. Incorporated them in the dashboard
