### ISSUE TITLE
NO2 color range

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#50]
We should mimmick the color range that the current NO2 products follow. This repo contains info about the color bar: https://gitlab.com/zfasnacht/global_mapping/-/tree/master/Colorbars

**Comment by olafveerman** [comment]
Blocked by: https://github.com/NASA-IMPACT/covid-dashboard/issues/61

**Comment by drewbo** [comment]
@olafveerman so it looks like this is a pretty custom colormap (converted to RGB [here](https://gist.github.com/drewbo/bdcdadc107c03008ac1bad18950a8ed0)); should we add this as an option to the tiler?

**Comment by drewbo** [comment]
Implemented in the API [here](https://github.com/NASA-IMPACT/covid-api/pull/11); @danielfdsilva to use on the front-end, replace `magma` with `custom_no2`
