### ISSUE TITLE
Define Indicator API pattern

### ISSUE THREAD

**Issue by drewbo** [NASA-IMPACT/covid-dashboard#54]
Show how spotlight location indicator data can be queried from the API

**Comment by drewbo** [comment]
Example at: https://8ib71h0627.execute-api.us-east-1.amazonaws.com/v1/sites/be

All indicator data is only accessible through the sites endpoint; @danielfdsilva please review and let me know if this looks easy to use on the front end

**Comment by danielfdsilva** [comment]
Would it be possible to change `indicator` to `value`. That would make it a bit more standard.
Also, since we are getting the data for charts from the api, it would be good to have some meta information as well, like, label and units. (Or should we keep this hardcoded?)

**Comment by drewbo** [comment]
@danielfdsilva I'm going to leave as indicator because it's likely that there are other keys in the payload as well (indicator confidence intervals, baseline confidence intervals, etc); I will add labels and units 👍

**Comment by olafveerman** [comment]
Based on the data Zach just sent over, here's a possible `metadata.json`:

``` json
{
  "name": "Nitrogren Dioxide",
  "units": "",
  "description": "15 day rolling average",
  "source": "OMI",
  "date": {
    "column": "date_obs",
    "format": "%d/%m/%Y"
  },
  "indicator": {
    "column": "median"
  },
  "baseline": {
    "column": "baseline_median"
  }
}
```

**Comment by olafveerman** [comment]
@drewbo What do you think about this proposal ^?

Particularly interested (unsure) about the following props. They are meant to populate legends:

* `indicator.description`
* `baseline.description` 

Alternatively, we can have a base-level object along these lines:

```
"legend": {
  "baseline": "Median values for same time window in 2015 - 2019",
  "indicator": "15 day rolling average"
}
```

**Comment by drewbo** [comment]
@olafveerman I like the first option for the description props

**Comment by danielfdsilva** [comment]
From the frontend point of view, the more data comes from the api the better, so this is helpful.
We just have to be mindful of how we describe the values. There has to be a match between what we show in the chart and have a description for. I guess this is more relevant for confidence areas, where we may have two values (top, bottom) but only one description.

**Comment by olafveerman** [comment]
This is fixed.
