### ISSUE TITLE
COG color maps

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#61]
Document how to add COG color maps

**Comment by drewbo** [comment]
Current options are [matplotlib colormaps](https://matplotlib.org/3.1.0/tutorials/colors/colormaps.html); adding a new map requires updates to the tiler code (not easily documentable)

**Comment by olafveerman** [comment]
@drewbo Thanks. For my own understanding:

* custom color profiles are added to the tiler
* the frontend can request COG with a specific color profile

**Comment by drewbo** [comment]
will be added in the next deploy

<img width="1132" alt="Screen Shot 2020-05-27 at 5 35 38 PM" src="https://user-images.githubusercontent.com/7108211/83074651-86e92980-a040-11ea-9bed-931ad2d03f13.png">

**Comment by olafveerman** [comment]
Closing, this was implemented
