### ISSUE TITLE
Add lock-down highlight to chart

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#88]
Add:

- [ ] lockdown dates to each spotlight area in the API
- [ ] show on the charts

**Comment by olafveerman** [comment]
https://en.wikipedia.org/wiki/National_responses_to_the_COVID-19_pandemic

**Comment by olafveerman** [comment]
First step is to figure out the lockdown dates for each of the spotlight areas.

**Comment by vgeorge** [comment]
id | name | date | obs
-- | -- | -- | --
be | Beijing | 23/jan/2020 | This is the date major chinese cities started lockdown, unclear if includes Beijing
du | Port of Dunkirk | March/16 |  
gh | Port of Ghent | March/18 |  
la | Los Angeles | March/19 |  
ny | New York | March/22 |  
sf | San Francisco | March/19 |  
jp | Tokye | April/06 | State of emergency, lockdowns are not allowed in Japan

**Comment by olafveerman** [comment]
Thanks @vgeorge 
Do these have end dates as well? Or are they all in progress?

**Comment by vgeorge** [comment]
@olafveerman the table above was updated with end dates or ongoing lockdowns.

**Comment by olafveerman** [comment]
Lockdown added to the API. 

Thanks @vgeorge for researching.
