### ISSUE TITLE
API support for highlight areas

### ISSUE THREAD

**Issue by olafveerman** [NASA-IMPACT/covid-dashboard#96]
* [chart documentation](https://github.com/NASA-IMPACT/covid-api/blob/master/guidelines/data-usage.md#highlight-bands---optional)
* docs for [data contributors](https://github.com/NASA-IMPACT/covid-api/blob/master/guidelines/indicators.md#optional-fields)

@danielfdsilva @drewbo So, the idea of adding this to the `metadata.json` doesn't work. We have a single file per indicator, and won't be able to add spotlight specific highlight bands. Unless we want to do something like in the `metadata.json`:

```
highlight_bands: [
  {
    area: 'be',
    dates: ...
    label: ...
  },
  {
    area: 'tk',
    dates: ...
  }
]
```

This results in a lot of config.

## Aternative 1. Only support spotlight specific highlights
Only support spotlight specific highlights. This will mostly be used for something like the lockdown.

## Option 2. Support a mix
Allow users to specify highlight bands in both the spotlight area config and the metadata.json.

This makes it very flexible, but may be a good example of a premature optimization.

**Comment by danielfdsilva** [comment]
I agree with @olafveerman that giving too much flexibility may be premature optimization and make the process of defining bands more complicated.
We should go with 1 and provide a set of optional bands to be set, which for now would probably be only lockdown

**Comment by drewbo** [comment]
Now that we have indicator x site specific descriptions, we can combine these into one metadata json; I'll write up a PR/proposal

**Comment by olafveerman** [comment]
This was implemented and looks :hot_pepper: 

![image](https://user-images.githubusercontent.com/751330/85646422-0bdc5880-b66a-11ea-9842-0ddb220a5752.png)
